name = "pgl"
version = "1.1.0"

description = "A Postgres driver written in gleam"
licences = ["MIT"]
repository = { type = "github", user = "stndrs", repo = "pgl" }
target = "erlang"

internal_modules = [
  "pgl/internal/*",
  "pgl/internal"
]

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
gleam_crypto = ">= 1.5.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_time = ">= 1.2.0 and < 2.0.0"
pg_value = ">= 1.0.0 and < 2.0.0"
db_pool = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
global_value = ">= 1.0.0 and < 2.0.0"
