name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_pg_15:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pgl_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Enable SSL and create test users
        run: ./scripts/setup-postgres-ci.sh postgres:15
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.18"
          rebar3-version: "3"
          # ImageOS: ubuntu20
      - run: gleam build
      - run: gleam test
      - run: gleam format --check src test
  test_pg_16:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pgl_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Enable SSL and create test users
        run: ./scripts/setup-postgres-ci.sh postgres:16
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.18"
          rebar3-version: "3"
          # ImageOS: ubuntu20
      - run: gleam build
      - run: gleam test
      - run: gleam format --check src test
  test_pg_17:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pgl_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Enable SSL and create test users
        run: ./scripts/setup-postgres-ci.sh postgres:17
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.18"
          rebar3-version: "3"
          # ImageOS: ubuntu20
      - run: gleam build
      - run: gleam test
      - run: gleam format --check src test
  test:
    runs-on: ubuntu-latest
    # container: ubuntu:20.04
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pgl_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Enable SSL and create test users
        run: ./scripts/setup-postgres-ci.sh postgres:18
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.18"
          rebar3-version: "3"
          # ImageOS: ubuntu20
      - run: gleam build
      - run: gleam test
      - run: gleam format --check src test
